version: "2"

services:
  caddy:
    build: ./caddy
    ports:
      - 98:80 
      - 443:443
    links:
      - wordpress
  
  wordpress:
    image: wordpress  
    volumes: 
      - ./wordpress/var/www/html:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8082:80"
    environment:
        MYSQL_USERNAME: "root"
        MYSQL_ROOT_PASSWORD: "password"
        PMA_HOST: "mysql"
        PMA_PORT: "3306"
      
  mysql:
    image: mysql
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "wordpress"
    restart: always
